<?php

namespace AppBundle\Repository\Entity;

/**
 * nosotrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nosotrosRepository extends \Doctrine\ORM\EntityRepository
{
}
