<?php

namespace AppBundle\Repository;

/**
 * ObrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObrasRepository extends \Doctrine\ORM\EntityRepository
{
}
